---
#Dont change this
version: 0
# Configuration

# Do u want to Enable the Customies Node?
CustomiesNode: true
# HumanNode will always be on (for now)

#more configuration stuff comes in the future ^^
...